### ISSUE TITLE
mkdocs build

### ISSUE THREAD

**Issue by beckf** [DurhamAcademy/darcside-docs#2]
mkdocs doesn't like something in the nav.  Perhaps it doesn't support nesting deeper than one level?  I will investigate. 
https://6502.team/docs/

**Comment by trevnels** [comment]
It looks correct from here. Mkdocs does support multiple levels of nesting, but it can't nest a page inside another page. It treats nesting like a normal folder structure, where something like `General > Administrative > Handbook` exists but `General > Administrative` isn't a page itself. There is a feature flag `navigation.indexes` to change this, but it's only available to mkdocs-material insiders for a certain period of time.

**Comment by beckf** [comment]
I see it now. Tricked by the cached.
